/***********************************************************************/
/*                                                                     */
/*  FILE        :include.h                                             */
/*  DATE        :Thu, Feb 28, 2013                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :RX610                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.53).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/*                                                                     */
/***********************************************************************/

// Include C standard library here
#include <machine.h>
#include <stdio.h>
#include <string.h>
#include "lowsrc.h"
// MCU IO definition library
#include "iodefine.h"

// Include self-defined library here
#include "main.h"
#include "const_def.h"
#include "port_def.h"
#include "mcu_info.h"
#include "ram.h"
#include "table.h"

/*** Data flash ***/
#include "r_flash_api_rx600.h"
#include "r_flash_api_rx600_config.h"
#include "r_flash_api_rx600_private.h"

/*** Switch ***/
#include "m_switch.h"
#include "m_switch_ram.h"
#include "m_switch_const_def.h"

/*** Led ***/
#include "m_led.h"
#include "m_led_ram.h"
#include "m_led_table.h"
#include "m_led_const_def.h"

/*** Nor flash ***/
#include "m_nor.h"
#include "m_nor_ram.h"
#include "m_nor_table.h"
#include "m_nor_const_def.h"




