/***********************************************************************/
/*                                                                     */
/*  FILE        :SirenRecogn.c                                         */
/*  DATE        :Thu, Feb 28, 2013                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :RX610                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.53).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/*                                                                     */
/***********************************************************************/

void main(void);



/****************************************************************************/
/* 		Init routines														*/
#if 1
// Init system clock
void initSysClock();

// Init SFRs
void initSfr();

#endif
/* 		End of Init routines												*/
/****************************************************************************/



/****************************************************************************/
/* 		Operation               											*/
#if 1
// Set operate
void operate();

#endif
/* 		End of Operation													*/
/****************************************************************************/




/****************************************************************************/
/* 		Counter, wait														*/
#if 1
// Count time
void countTime();

// Wait n x 10ms
void wait10ms(unsigned short interval);

// Wait n x mc
void waitNmc(unsigned short interval);

#endif
/*		End of WAIT															*/
/****************************************************************************/

