/***********************************************************************/
/*                                                                     */
/*  FILE        :ram.c		                                           */
/*  DATE        :Thu, Feb 28, 2013                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :RX610                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.53).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/*                                                                     */
/***********************************************************************/

















