/***********************************************************************/
/*                                                                     */
/*  FILE        :SirenRecogn.c                                         */
/*  DATE        :Thu, Feb 28, 2013                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :RX610                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.53).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/*                                                                     */
/***********************************************************************/


/*** Model and version management ***/
extern const unsigned char modelTbl[18];

/*** 8 bit mask table ***/
extern const unsigned char uint8Tbl[8];

/*** 16 bit mask table ***/
extern const unsigned short uint16Tbl[16];

/*** 32 bit mask table ***/
extern const unsigned long uint32Tbl[32];




