/***********************************************************************/
/*                                                                     */
/*  FILE        :m_nor_ram.h                                        */
/*  DATE        :Thu, Feb 28, 2013                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :RX610                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.53).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/*                                                                     */
/***********************************************************************/
#ifndef _M_NOR_RAM_H
#define _M_NOR_RAM_H
#endif
#ifdef _M_NOR_RAM_H
/*** Nor flash global variables ***/
extern unsigned short norTm;
extern unsigned char norMode;
extern unsigned char norSeq;
extern unsigned char busyFlg;

/*VARIABLES TIME*/
extern unsigned char startTime;
extern unsigned char elapsedTime;
extern unsigned char flgTm;


struct stNor {
	unsigned short manufacturerCode;
	unsigned short deviceCode1;
	unsigned short deviceCode2;
	unsigned short deviceCode3;
	// unsigned short unprotected;
	
	// unsigned char status[3];
};

extern struct stNor norCode[6];


struct stNorStatus {
	unsigned char busyFlg;
	unsigned char status[3];
};
extern struct stNorStatus nor;

extern unsigned short norBusyTm;
extern unsigned short dBuff[32];
extern unsigned short data1[32];
extern unsigned short wBuff[10];

#endif













