/***********************************************************************/
/*                                                                     */
/*  FILE        :m_nor_table.h                                         */
/*  DATE        :Thu, Feb 28, 2013                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :RX610                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.53).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/*                                                                     */
/***********************************************************************/
#ifndef _M_NOR_TABLE_H
#define _M_NOR_TABLE_H
#endif
#ifdef _M_NOR_TABLE_H
/*** Nor flash reference table ***/
extern const unsigned short* norCsAddrTbl[6];


#endif













