/***********************************************************************/
/*                                                                     */
/*  FILE        :m_nor_ram.c                                         */
/*  DATE        :Thu, Feb 28, 2013                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :RX610                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.53).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/*                                                                     */
/***********************************************************************/
#include "include.h"


#if 1
/*** Nor flash global variables ***/
unsigned short norTm;
unsigned char norMode;
unsigned char norSeq;
unsigned char busyFlg;



/*VARIABLES TIME*/
unsigned char startTime;
unsigned char elapsedTime;
unsigned char flgTm;




// struct stNor {
// 	unsigned short manufacturerCode;
// 	unsigned short deviceCode1;
// 	unsigned short deviceCode2;
// 	unsigned short deviceCode3;
// };
struct stNor norCode[6];

// struct stNorStatus {
// 	unsigned char busyFlg;
// 	unsigned char status[3];
// };
struct stNorStatus nor;

unsigned short norBusyTm;
unsigned short dBuff[32];
unsigned short data1[32];
unsigned short wBuff[10] = {1,2,3,4,5,6,7,8,9,0};

#endif










