/***********************************************************************/
/*                                                                     */
/*  FILE        :m_nor_table.c                                         */
/*  DATE        :Thu, Feb 28, 2013                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :RX610                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.53).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/*                                                                     */
/***********************************************************************/
#include "include.h"


#if 1
/*** Nor flash reference table ***/
const unsigned short* norCsAddrTbl[6] = {
	CS1_POS,
	CS2_POS,
	CS3_POS,
	CS4_POS,
	CS5_POS,
	CS6_POS
};


#endif










