/***********************************************************************/
/*                                                                     */
/*  FILE        :m_nor.h                                               */
/*  DATE        :Thu, Feb 28, 2013                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :RX610                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.53).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/*                                                                     */
/***********************************************************************/
#ifndef _M_NOR_H
#define _M_NOR_H
#endif

#ifdef _M_NOR_H

/****************************************************************************/
/* 		setNor																*/
#if 1
// Set NOR Flash
void setNor();

#endif
/* 		End of setNor														*/
/****************************************************************************/


/****************************************************************************/
/* 		readNor, writeNor, etc.												*/
#if 1
// Read data from Nor flash
unsigned char readNor(unsigned char  chipNo,unsigned long sAddr, unsigned short* dPos, unsigned short length);
//
unsigned char readPage(unsigned char chipNo, unsigned long sAddr,unsigned short* dPos, unsigned short length);

// Write data to Nor flash
unsigned char writeNor(unsigned char chipNo,unsigned long dAddr, unsigned short* sPos, unsigned short length);

// Erase block of Nor flash
unsigned char eraseNorBlock(unsigned char chipNo, unsigned short blockNo);

// Erase chip
unsigned char eraseNorChip(unsigned char chipNo);

// Read device ID of Nor flash
unsigned char readNorDeviceId(unsigned char chipNo);

// blank check
unsigned char blankCheck(unsigned char chipNo, unsigned short blockNo);
#endif
/* 		End of readNor, writeNor, etc.										*/
/****************************************************************************/


/****************************************************************************/
/* 		setNorAddr, sendNorCmd, etc.										*/
#if 1
// Set Nor Flash Address
void setNorAddrA25A24A23(unsigned long addr);


// Send Nor Flash Command
void sendNorCmd(unsigned char chipNo, unsigned long cmd);

// Send Nor Flash Command
void sendAddrCmd(unsigned char chipNo, unsigned long cmdAddr);

// Send data to a specific address
void sendNorData(unsigned char chipNo, unsigned long destAddr, unsigned short data);

// Read 1 word from NOR flash
unsigned short readNorWord(unsigned char chipNo, unsigned long sourceAddr);

// Read 1 word from NOR flash
unsigned short readWord(unsigned char chipNo, unsigned long sourceAddr);

// Read 1 byte from NOR flash
unsigned char readNorByte(unsigned char chipNo, unsigned long sourceAddr);

// Reset cmd
void reset(unsigned char ChipNo);


// Nor bit togle
unsigned char norBitTogle(unsigned char chipNo, unsigned long timeout, unsigned char mode);

//set nor flash resume
unsigned char setNorResume(unsigned char chipNo);

// set nor flash suspend
unsigned char setNorSuspend(unsigned char chipNo);
#endif
/* 		End of setNorAddr, sendNorCmd, etc.									*/
/****************************************************************************/


/****************************************************************************/
/*                       Time                                               */
unsigned char chktimeout(unsigned long timeout, unsigned char mode);
// Off calcultor check timeout
void chktimeout_off();




/****************************************************************************/
/*                   Protection Function Prototypes                         */
unsigned char checkBlockProtection(unsigned short blockNo);
#endif
