/***********************************************************************/
/*                                                                     */
/*  FILE        :m_switch.h                                            */
/*  DATE        :Thu, Feb 28, 2013                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :RX610                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.53).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/*                                                                     */
/***********************************************************************/

/****************************************************************************/
/* 		getAllSw, etc														*/
#if 1
// Get all switch state
void getAllSwState();

// Process all switch state
void processAllSwState();

// Get single switch state
void getSingleSw(unsigned char swValue, unsigned char swIndex);

#endif
/*		End of WAIT															*/
/****************************************************************************/

