/***********************************************************************/
/*                                                                     */
/*  FILE        :m_switch_ram.h                                        */
/*  DATE        :Thu, Feb 28, 2013                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :RX610                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.53).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/*                                                                     */
/***********************************************************************/
#ifndef _M_SWITCH_RAM_H
#define _M_SWITCH_RAM_H
#endif
#ifdef _M_SWITCH_RAM_H
/*** Global variables of switch ***/
extern unsigned char swState;
extern unsigned char swStateBak;
extern unsigned char swStateFlg;

extern unsigned short swTm;
extern unsigned char swMode;
extern unsigned char swSeq;


#endif













