/***********************************************************************/
/*                                                                     */
/*  FILE        :m_switch_ram.c                                         */
/*  DATE        :Thu, Feb 28, 2013                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :RX610                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.53).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/*                                                                     */
/***********************************************************************/



#if 1
/*** Global variables of switch ***/
unsigned char swState;
unsigned char swStateBak;
unsigned char swStateFlg;

unsigned short swTm;
unsigned char swMode;
unsigned char swSeq;

#endif










