/***********************************************************************/
/*                                                                     */
/*  FILE        :m_led_table.h                                         */
/*  DATE        :Thu, Feb 28, 2013                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :RX610                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.53).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/*                                                                     */
/***********************************************************************/
#ifndef _M_LED_TABLE_H
#define _M_LED_TABLE_H
#endif
#ifdef _M_LED_TABLE_H
/*** Character table of LED7 segment ***/
extern const unsigned char led7SegCharTbl[37];

#endif













