/***********************************************************************/
/*                                                                     */
/*  FILE        :m_led_table.c                                         */
/*  DATE        :Thu, Feb 28, 2013                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :RX610                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.53).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/*                                                                     */
/***********************************************************************/
#include "include.h"


#if 1
/*** Character table of LED7 segment ***/
const unsigned char led7SegCharTbl[37] = {
	0xC0,	// 0
	0xF9,	// 1
	0xA4,	// 2
	0xB0,	// 3
	0x99,	// 4
	0x92,	// 5
	0x82,	// 6
	0xF8,	// 7
	0x80,	// 8
	0x90,	// 9
	0x88,	// A
	0x83,	// B
	0xC6,	// C
	0xA1,	// D
	0x86,	// E
	0x8E,	// F
	//0x8B,	// H
	0x89,	// H
	0xCF,	// I
	0xC7,	// L
	//0xAB,	// N
	0xC8,	// N
	0xE3,	// O
	0x8C,	// P
	0xAF,	// R
	0x92,	// S
	0x87,	// T
	0xC1,	// U
	0xBF,	// -
	0xB7,	// =
	0xFF,	// Space
	0x7F,	// DP
	0xB6,	// 三
	0xF7,	// -
	0xFE,	// _
	0x8F,	// H
	0xE3,	// u
	0xA3,	// o
	0xA1	// d
};



#endif










