/***********************************************************************/
/*                                                                     */
/*  FILE        :m_led.h                                               */
/*  DATE        :Thu, Feb 28, 2013                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :RX610                                                 */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.53).    */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/*                                                                     */
/***********************************************************************/

/****************************************************************************/
/* 		setAllLed, etc														*/
#if 1
// Set all LEDs
void setAllLeds();

// Output all LEDs
void outputAllLeds(unsigned short ledValue);

// Output single LED
unsigned char outputSingleLed(unsigned short ledValue, unsigned char ledIndex);

#endif
/*		End of setAllLed													*/
/****************************************************************************/


/****************************************************************************/
/* 		setLed7, etc														*/
#if 1
// Set LED 7
void setLed7();

#endif
/*		End of setLed7														*/
/****************************************************************************/


/****************************************************************************/
/* 		LED7 output 														*/
#if 1
// Output all LED7
void outputAllLed7(unsigned char* sPos);

// Output single LED7
void outputSingleLed7(unsigned char ledIndex, unsigned char data);

// Set LED7 Driver to output mode
void setLed7Output();

#endif
/*		End of LED7 output													*/
/****************************************************************************/


/****************************************************************************/
/* 		LED7 driver 														*/
#if 1
// Write LED7 data
void writeLed7(unsigned char ledIndex, unsigned char data);

// Write data to LED7 driver
unsigned char writeLed7Driver(unsigned char chipAddr, unsigned char regAddr, unsigned char data);

// Set start condition on I2C bus
void setI2CStartCondition();

// Set stop condition on I2C bus
void setI2CStopCondition();

// Output 8 bit and check ack
unsigned char writeI2CDataAndCheckAck(unsigned char data);

// Check ACK from I2C bus
unsigned char checkI2CAck();

#endif
/*		End of LED7 driver													*/
/****************************************************************************/

